import torch
import torch.export
from torch.export import export
from transformers import AutoModelForCausalLM
from typing import Dict, Any, List

# ==============================================================================
# 1. ATen Operator to tensor_graphs_cpp Lowering Table
# ==============================================================================
# ATen ops generated by torch.export are canonicalized (e.g. aten.add.Tensor)
ATEN_LOWERING = {
    # Matrix Multiplications
    "aten.mm.default": "dot",
    "aten.bmm.default": "dot",
    "aten.matmul.default": "dot",

    # Element-wise Arithmetic
    "aten.add.Tensor": "add",
    "aten.sub.Tensor": "sub", # or g.add(a, g.neg(b))
    "aten.mul.Tensor": "mul",
    "aten.div.Tensor": "div",
    "aten.pow.Tensor_Tensor": "pow",
    "aten.pow.Tensor_Scalar": "pow",
    "aten.neg.default": "neg",

    # Trigonometric / Transcendental
    "aten.sin.default": "sin",
    "aten.cos.default": "cos",
    "aten.log.default": "log",

    # Shape & View Operations
    "aten.view.default": "reshape",
    "aten.reshape.default": "reshape",
    "aten.permute.default": "permute",
    "aten.transpose.int": "permute",
    "aten.slice.Tensor": "slice",
    "aten.cat.default": "concat",
    "aten.repeat.default": "repeat",

    # Reductions & Indexing
    "aten.sum.dim_IntList": "sum",
    "aten.max.dim": "max",
    "aten.embedding.default": "gather",
    "aten.select.int": "slice",
}


# ==============================================================================
# 2. C++ Code Generator Emitter
# ==============================================================================
class TensorGraphCodeEmitter:
    def __init__(self, model_name: str, weight_path: str):
        self.model_name = model_name
        self.weight_path = weight_path
        self.code_lines: List[str] = []
        self.node_vars: Dict[str, str] = {} # FX Node Name -> C++ LogicalId variable

    def emit_header(self):
        self.code_lines.extend([
            "#pragma once",
            "#include \"core/graph.hpp\"",
            "#include \"core/types.hpp\"",
            "",
            "// Auto-generated by transpile_gemma.py using torch.export",
            f"class {self.model_name}Generated {{",
            "public:",
            "    Graph &g;",
            "    const std::string w_path;",
            "",
            f"    {self.model_name}Generated(Graph &graph, const std::string &weight_path)",
            "        : g(graph), w_path(weight_path) {}",
            "",
            "    LogicalId build_graph(LogicalId input_ids) {",
        ])

    def emit_footer(self, final_var_name: str) -> str:
        final_cpp_var = self.node_vars.get(final_var_name, "LogicalId()")
        self.code_lines.extend([
            f"        return {final_cpp_var};",
            "    }",
            "};"
        ])
        return "\n".join(self.code_lines)

    def register_node(self, fx_node_name: str, cpp_var: str):
        # Sanitize variable names for C++ (e.g., replace '.' with '_')
        clean_name = f"var_{fx_node_name.replace('.', '_')}"
        self.node_vars[fx_node_name] = clean_name
        return clean_name


# 1. Define a clean wrapper to strip HF custom classes & disable KV Cache
class GemmaExportWrapper(torch.nn.Module):
    def __init__(self, model):
        super().__init__()
        self.model = model

    def forward(self, input_ids):
        # use_cache=False: prevents creation of DynamicCache
        # return_dict=False: returns raw tuple (logits, ...) instead of CausalLMOutput
        outputs = self.model(input_ids, use_cache=False, return_dict=False)
        
        # Return only the logits Tensor so torch.export sees pure Tensor outputs
        logits = outputs[0]
        return logits


def transpile_gemma_3():
    model_path = "./models/google/gemma-3-270m"
    print(f"[1/4] Loading HF Model: {model_path}...")
    
    # Load model in float32 for clean C++ lowering
    model = AutoModelForCausalLM.from_pretrained(
        model_path,
        dtype=torch.float32,          # Updated per transformers deprecation warning
        attn_implementation="eager"   # Ensures standard ATen ops instead of opaque CUDA blobs
    )
    model.eval()

    # Wrap the model
    wrapped_model = GemmaExportWrapper(model)

    # Dummy inputs for export (e.g. sequence length 8)
    dummy_input_ids = torch.randint(0, 1000, (1, 8), dtype=torch.int32)

    print("[2/4] Exporting model with torch.export.export()...")
    
    # Export the wrapped model instead of the raw HF model
    exported_program: torch.export.ExportedProgram = export(
        wrapped_model, 
        (dummy_input_ids,)
    )

    print("Export successful!")
    
    # Extract signature and graph module
    graph_module = exported_program.graph_module
    signature = exported_program.graph_signature

    # Note: When using a wrapper, parameter nodes are mapped through `self.model`
    param_map = {}
    for node_name, param_name in signature.inputs_to_parameters.items():
        # Remove 'model.' prefix added by wrapper if necessary
        clean_param_name = param_name.removeprefix("model.")
        param_map[node_name] = clean_param_name
    for node_name, buffer_name in signature.inputs_to_buffers.items():
        clean_buffer_name = buffer_name.removeprefix("model.")
        param_map[node_name] = clean_buffer_name

    print("[3/4] Lowering FX ATen graph to tensor_graphs_cpp...")
    emitter = TensorGraphCodeEmitter("Gemma3_270M", "models/gemma-3-270m/model.safetensors")
    emitter.emit_header()

    # Traverse FX graph nodes in topological execution order
    for node in graph_module.graph.nodes:
        # A. Placeholder Nodes (Inputs vs Weights)
        if node.op == "placeholder":
            if node.name in signature.user_inputs:
                # Runtime input (e.g. input_ids)
                cpp_var = emitter.register_node(node.name, "input_ids")
                emitter.code_lines.append(f"        // Input: {node.name}")
                emitter.node_vars[node.name] = "input_ids"
            elif node.name in param_map:
                # Model weight -> g.weight(w_path, "model.layers.0...")
                hf_weight_key = param_map[node.name]
                cpp_var = emitter.register_node(node.name, "")
                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.cast(g.weight(w_path, \"{hf_weight_key}\"), DType::FLOAT32);"
                )

        # B. Call Function Nodes (ATen Ops)
        elif node.op == "call_function":
            op_target_str = str(node.target)
            cpp_var = emitter.register_node(node.name, "")

            if op_target_str in ATEN_LOWERING:
                tg_method = ATEN_LOWERING[op_target_str]
                
                # Resolve C++ variable names for arguments
                cpp_args = []
                for arg in node.args:
                    if isinstance(arg, torch.fx.Node):
                        cpp_args.append(emitter.node_vars[arg.name])
                    elif isinstance(arg, (int, float, list, tuple)):
                        # Handle constants/scalars by converting to g.constant or shape arrays
                        cpp_args.append(str(arg))

                # Special handling for MatMul / Dot layout
                if tg_method == "dot":
                    emitter.code_lines.append(
                        f"        LogicalId {cpp_var} = g.dot({cpp_args[0]}, {cpp_args[1]});"
                    )
                # Special handling for Reshape / View
                elif tg_method == "reshape":
                    shape_arg = cpp_args[1] # Target shape
                    emitter.code_lines.append(
                        f"        int32_t shape_{cpp_var}[] = {shape_arg.replace('[', '{').replace(']', '}')};"
                    )
                    emitter.code_lines.append(
                        f"        LogicalId {cpp_var} = g.reshape({cpp_args[0]}, g.constant({{ {len(node.args[1])} }}, shape_{cpp_var}, DType::INT32));"
                    )
                # Generic Element-wise Op
                else:
                    args_str = ", ".join(cpp_args)
                    emitter.code_lines.append(
                        f"        LogicalId {cpp_var} = g.{tg_method}({args_str});"
                    )
            else:
                emitter.code_lines.append(
                    f"        // UNHANDLED ATen Op: {op_target_str} for node {node.name}"
                )

        # C. Output Node
        elif node.op == "output":
            final_node = node.args[0][0] if isinstance(node.args[0], (list, tuple)) else node.args[0]
            emitter.emit_footer(final_node.name)

    print("[4/4] Writing generated C++ header file...")
    cpp_source = emitter.code_lines
    output_filename = "tensor_graphs_cpp/models/gemma-3-270m-generated.hpp"
    with open(output_filename, "w") as f:
        f.write("\n".join(cpp_source))
    print(f"Successfully generated: {output_filename}")


if __name__ == "__main__":
    transpile_gemma_3()