import torch
import torch.export
from torch.export import export
from transformers import AutoModelForCausalLM, AutoConfig
from typing import Dict, Any, List

# ==============================================================================
# 1. Torch DType to C++ DType Mapping
# ==============================================================================
TORCH_DTYPE_TO_TG = {
    torch.float32: "DType::FLOAT32",
    torch.float: "DType::FLOAT32",
    torch.float16: "DType::BF16",
    torch.bfloat16: "DType::BF16",
    torch.int32: "DType::INT32",
    torch.int: "DType::INT32",
    torch.int64: "DType::INT64",
    torch.long: "DType::INT64",
    torch.bool: "DType::BOOL",
}


# ==============================================================================
# 2. C++ Code Generator Emitter
# ==============================================================================
class TensorGraphCodeEmitter:
    def __init__(self, model_name: str, weight_path: str):
        self.model_name = model_name
        self.weight_path = weight_path
        self.code_lines: List[str] = []
        self.node_vars: Dict[str, str] = {}  # FX Node Name -> C++ LogicalId variable
        self.var_counter = 0

    def get_unique_var(self, prefix: str = "tmp") -> str:
        self.var_counter += 1
        return f"{prefix}_{self.var_counter}"

    def emit_header(self):
        self.code_lines.extend(
            [
                "#pragma once",
                '#include "core/graph.hpp"',
                '#include "core/types.hpp"',
                "",
                "// Auto-generated by transpile_gemma.py using torch.export",
                f"class {self.model_name}Generated {{",
                "public:",
                "    Graph &g;",
                "    const std::string w_path;",
                "",
                f"    {self.model_name}Generated(Graph &graph, const std::string &weight_path)",
                "        : g(graph), w_path(weight_path) {}",
                "",
                "    LogicalId build_graph(LogicalId input_ids) {",
            ]
        )

    def emit_footer(self, final_var_name: str) -> str:
        final_cpp_var = self.node_vars.get(final_var_name, "LogicalId()")
        self.code_lines.extend([f"        return {final_cpp_var};", "    }", "};"])
        return "\n".join(self.code_lines)

    def register_node(self, fx_node_name: str, cpp_var: str = "") -> str:
        clean_name = cpp_var if cpp_var else f"var_{fx_node_name.replace('.', '_')}"
        self.node_vars[fx_node_name] = clean_name
        return clean_name

    def ensure_logical_id(self, arg: Any) -> str:
        """Ensures an argument is converted to a C++ LogicalId variable name."""
        if isinstance(arg, torch.fx.Node):
            if arg.name in self.node_vars:
                return self.node_vars[arg.name]
            return f"var_{arg.name.replace('.', '_')}"
        elif isinstance(arg, bool):
            v_name = self.get_unique_var("bool")
            val_str = "true" if arg else "false"
            self.code_lines.append(f"        bool val_{v_name} = {val_str};")
            self.code_lines.append(
                f"        LogicalId {v_name} = g.constant({{1}}, &val_{v_name}, DType::BOOL);"
            )
            return v_name
        elif isinstance(arg, int):
            v_name = self.get_unique_var("int")
            self.code_lines.append(f"        int32_t val_{v_name} = {arg};")
            self.code_lines.append(
                f"        LogicalId {v_name} = g.constant({{1}}, &val_{v_name}, DType::INT32);"
            )
            return v_name
        elif isinstance(arg, float):
            v_name = self.get_unique_var("float")
            self.code_lines.append(f"        float val_{v_name} = {arg}f;")
            self.code_lines.append(
                f"        LogicalId {v_name} = g.constant({{1}}, &val_{v_name}, DType::FLOAT32);"
            )
            return v_name
        elif isinstance(arg, str) and arg in self.node_vars.values():
            return arg
        else:
            v_name = self.get_unique_var("val")
            self.code_lines.append(
                f"        float val_{v_name} = static_cast<float>({arg});"
            )
            self.code_lines.append(
                f"        LogicalId {v_name} = g.constant({{1}}, &val_{v_name}, DType::FLOAT32);"
            )
            return v_name


# 1. Define a clean wrapper to strip HF custom classes & disable KV Cache
class GemmaExportWrapper(torch.nn.Module):
    def __init__(self, model):
        super().__init__()
        self.model = model

    def forward(self, input_ids):
        # use_cache=False: prevents creation of DynamicCache
        # return_dict=False: returns raw tuple (logits, ...) instead of CausalLMOutput
        outputs = self.model(input_ids, use_cache=False, return_dict=False)

        # Return only the logits Tensor so torch.export sees pure Tensor outputs
        logits = outputs[0]
        return logits


def transpile_gemma_3():
    model_path = "./models/google/gemma-3-270m"
    print(f"[1/4] Reading Config (NO WEIGHTS) from: {model_path}...")

    # 1. Load ONLY the JSON config file (no weights are touched)
    config = AutoConfig.from_pretrained(model_path)

    # 2. Instantiate the model directly on the 'meta' device (takes 0 bytes of RAM)
    with torch.device("meta"):
        model = AutoModelForCausalLM.from_config(
            config, attn_implementation="eager"  # Use standard eager attention
        )
    model.eval()

    wrapped_model = GemmaExportWrapper(model)

    # 3. Create dummy inputs on the 'meta' device as well
    dummy_input_ids = torch.ones((1, 8), dtype=torch.int32, device="meta")

    print("[2/4] Exporting model on 'meta' device with torch.export.export()...")

    # PyTorch natively traces meta-device models symbolically
    exported_program: torch.export.ExportedProgram = export(
        wrapped_model, (dummy_input_ids,)
    )

    print("Meta-device export successful!")

    # 4. Extract signature and graph module
    graph_module = exported_program.graph_module
    signature = exported_program.graph_signature

    # All parameter names and graph operations are fully intact!
    param_map = {}
    for node_name, param_name in signature.inputs_to_parameters.items():
        clean_param_name = param_name.removeprefix("model.")
        param_map[node_name] = clean_param_name
    for node_name, buffer_name in signature.inputs_to_buffers.items():
        clean_buffer_name = buffer_name.removeprefix("model.")
        param_map[node_name] = clean_buffer_name

    print("[3/4] Lowering FX ATen graph to tensor_graphs_cpp...")
    emitter = TensorGraphCodeEmitter(
        "Gemma3_270M", "models/gemma-3-270m/model.safetensors"
    )
    emitter.emit_header()

    # Traverse FX graph nodes in topological execution order
    for node in graph_module.graph.nodes:
        # A. Placeholder Nodes (Inputs vs Weights)
        if node.op == "placeholder":
            if node.name in signature.user_inputs:
                # Runtime input (e.g. input_ids)
                cpp_var = emitter.register_node(node.name, "input_ids")
                emitter.code_lines.append(f"        // Input: {node.name}")
                emitter.node_vars[node.name] = "input_ids"
            elif node.name in param_map:
                # Model weight -> g.weight(w_path, "model.layers.0...")
                hf_weight_key = param_map[node.name]
                cpp_var = emitter.register_node(node.name)
                emitter.code_lines.append(
                    f'        LogicalId {cpp_var} = g.cast(g.weight(w_path, "{hf_weight_key}"), DType::FLOAT32);'
                )

        # B. Call Function Nodes (ATen Ops)
        elif node.op == "call_function":
            op_target_str = str(node.target)
            cpp_var = emitter.register_node(node.name)

            # Pass-through / Ignored / Assertion ATen Ops
            if any(
                skip_op in op_target_str
                for skip_op in (
                    "_assert_tensor_metadata",
                    "detach_",
                    "wrap_with_set_grad_enabled",
                )
            ):
                if node.args:
                    first_arg = node.args[0]
                    if isinstance(first_arg, torch.fx.Node):
                        emitter.node_vars[node.name] = emitter.ensure_logical_id(
                            first_arg
                        )
                continue

            # 1. Embedding / Gather (requires exactly 2 LogicalId arguments)
            if "embedding" in op_target_str or "gather" in op_target_str:
                id0 = emitter.ensure_logical_id(node.args[0])
                id1 = emitter.ensure_logical_id(node.args[1])
                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.gather({id0}, {id1});"
                )

            # 2. Cast / To DType (requires id0 and DType enum)
            elif (
                "to.dtype" in op_target_str
                or "type_as" in op_target_str
                or "cast" in op_target_str
            ):
                id0 = emitter.ensure_logical_id(node.args[0])
                target_dtype = "DType::FLOAT32"
                if len(node.args) > 1 and isinstance(node.args[1], torch.dtype):
                    target_dtype = TORCH_DTYPE_TO_TG.get(
                        node.args[1], "DType::FLOAT32"
                    )
                elif "dtype" in node.kwargs and isinstance(
                    node.kwargs["dtype"], torch.dtype
                ):
                    target_dtype = TORCH_DTYPE_TO_TG.get(
                        node.kwargs["dtype"], "DType::FLOAT32"
                    )
                elif (
                    hasattr(node, "meta")
                    and "val" in node.meta
                    and hasattr(node.meta["val"], "dtype")
                ):
                    target_dtype = TORCH_DTYPE_TO_TG.get(
                        node.meta["val"].dtype, "DType::FLOAT32"
                    )
                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.cast({id0}, {target_dtype});"
                )

            # 3. Addition
            elif "add" in op_target_str:
                id0 = emitter.ensure_logical_id(node.args[0])
                id1 = emitter.ensure_logical_id(node.args[1])
                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.add({id0}, {id1});"
                )

            # 4. Subtraction (g.add(a, g.neg(b)))
            elif "sub" in op_target_str:
                id0 = emitter.ensure_logical_id(node.args[0])
                id1 = emitter.ensure_logical_id(node.args[1])
                neg_var = emitter.get_unique_var("neg")
                emitter.code_lines.append(
                    f"        LogicalId {neg_var} = g.neg({id1});"
                )
                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.add({id0}, {neg_var});"
                )

            # 5. Multiplication
            elif "mul" in op_target_str:
                id0 = emitter.ensure_logical_id(node.args[0])
                id1 = emitter.ensure_logical_id(node.args[1])
                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.mul({id0}, {id1});"
                )

            # 6. Division
            elif "div" in op_target_str:
                id0 = emitter.ensure_logical_id(node.args[0])
                id1 = emitter.ensure_logical_id(node.args[1])
                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.div({id0}, {id1});"
                )

            # 7. Power
            elif "pow" in op_target_str:
                id0 = emitter.ensure_logical_id(node.args[0])
                id1 = emitter.ensure_logical_id(node.args[1])
                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.pow({id0}, {id1});"
                )

            # 8. Matrix Multiplication / Dot
            elif any(
                mm_op in op_target_str
                for mm_op in ("mm", "bmm", "matmul", "linear")
            ):
                id0 = emitter.ensure_logical_id(node.args[0])
                id1 = emitter.ensure_logical_id(node.args[1])
                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.dot({id0}, {id1});"
                )

            # 9. Negate
            elif "neg" in op_target_str:
                id0 = emitter.ensure_logical_id(node.args[0])
                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.neg({id0});"
                )

            # 10. Trigonometric / Transcendental
            elif "sin" in op_target_str:
                id0 = emitter.ensure_logical_id(node.args[0])
                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.sin({id0});"
                )
            elif "cos" in op_target_str:
                id0 = emitter.ensure_logical_id(node.args[0])
                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.cos({id0});"
                )
            elif "log" in op_target_str:
                id0 = emitter.ensure_logical_id(node.args[0])
                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.log({id0});"
                )

            # 11. Reshape / View / Unsqueeze / Squeeze
            elif any(
                r_op in op_target_str
                for r_op in ("view", "reshape", "unsqueeze", "squeeze")
            ):
                id0 = emitter.ensure_logical_id(node.args[0])
                shape_list = []
                if len(node.args) > 1 and isinstance(node.args[1], (list, tuple)):
                    shape_list = [
                        int(s) if isinstance(s, (int, float)) else -1
                        for s in node.args[1]
                    ]
                elif (
                    hasattr(node, "meta")
                    and "val" in node.meta
                    and hasattr(node.meta["val"], "shape")
                ):
                    shape_list = [int(s) for s in node.meta["val"].shape]

                if not shape_list:
                    shape_list = [1]

                shape_arr_var = f"shape_{cpp_var}"
                emitter.code_lines.append(
                    f"        int32_t {shape_arr_var}[] = {{ {', '.join(map(str, shape_list))} }};"
                )
                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.reshape({id0}, g.constant({{ {len(shape_list)} }}, {shape_arr_var}, DType::INT32));"
                )

            # 12. Permute / Transpose
            elif "permute" in op_target_str or "transpose" in op_target_str:
                id0 = emitter.ensure_logical_id(node.args[0])
                if "transpose" in op_target_str:
                    rank = 4
                    if (
                        hasattr(node.args[0], "meta")
                        and "val" in node.args[0].meta
                        and hasattr(node.args[0].meta["val"], "shape")
                    ):
                        rank = len(node.args[0].meta["val"].shape)
                    d0 = node.args[1] if len(node.args) > 1 else 0
                    d1 = node.args[2] if len(node.args) > 2 else 1
                    if isinstance(d0, int) and d0 < 0:
                        d0 += rank
                    if isinstance(d1, int) and d1 < 0:
                        d1 += rank
                    perm_dims = list(range(rank))
                    if (
                        isinstance(d0, int)
                        and isinstance(d1, int)
                        and d0 < rank
                        and d1 < rank
                    ):
                        perm_dims[d0], perm_dims[d1] = (
                            perm_dims[d1],
                            perm_dims[d0],
                        )
                else:
                    perm_dims = (
                        [int(d) for d in node.args[1]]
                        if len(node.args) > 1
                        and isinstance(node.args[1], (list, tuple))
                        else [0, 1]
                    )

                perm_arr_var = f"perm_{cpp_var}"
                emitter.code_lines.append(
                    f"        int32_t {perm_arr_var}[] = {{ {', '.join(map(str, perm_dims))} }};"
                )
                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.permute({id0}, g.constant({{ {len(perm_dims)} }}, {perm_arr_var}, DType::INT32));"
                )

            # 13. Slice / Select
            elif "slice" in op_target_str or "select" in op_target_str:
                id0 = emitter.ensure_logical_id(node.args[0])
                rank = 4
                if (
                    hasattr(node.args[0], "meta")
                    and "val" in node.args[0].meta
                    and hasattr(node.args[0].meta["val"], "shape")
                ):
                    rank = len(node.args[0].meta["val"].shape)

                dim = (
                    int(node.args[1])
                    if len(node.args) > 1 and isinstance(node.args[1], int)
                    else 0
                )
                if dim < 0:
                    dim += rank

                start = (
                    int(node.args[2])
                    if len(node.args) > 2
                    and node.args[2] is not None
                    and isinstance(node.args[2], int)
                    else 0
                )
                end = (
                    int(node.args[3])
                    if len(node.args) > 3
                    and node.args[3] is not None
                    and isinstance(node.args[3], int)
                    else 2147483647
                )
                step = (
                    int(node.args[4])
                    if len(node.args) > 4
                    and node.args[4] is not None
                    and isinstance(node.args[4], int)
                    else 1
                )

                starts = [0] * rank
                ends = [2147483647] * rank
                steps = [1] * rank

                if dim < rank:
                    starts[dim] = start
                    ends[dim] = end
                    steps[dim] = step

                emitter.code_lines.append(
                    f"        int32_t starts_{cpp_var}[] = {{ {', '.join(map(str, starts))} }};"
                )
                emitter.code_lines.append(
                    f"        int32_t ends_{cpp_var}[] = {{ {', '.join(map(str, ends))} }};"
                )
                emitter.code_lines.append(
                    f"        int32_t steps_{cpp_var}[] = {{ {', '.join(map(str, steps))} }};"
                )
                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.slice({id0}, "
                    f"g.constant({{ {len(starts)} }}, starts_{cpp_var}, DType::INT32), "
                    f"g.constant({{ {len(ends)} }}, ends_{cpp_var}, DType::INT32), "
                    f"g.constant({{ {len(steps)} }}, steps_{cpp_var}, DType::INT32));"
                )

            # 14. Concat / Cat
            elif "cat" in op_target_str or "concat" in op_target_str:
                tensor_nodes = (
                    node.args[0]
                    if len(node.args) > 0
                    and isinstance(node.args[0], (list, tuple))
                    else []
                )
                cpp_tensors = [emitter.ensure_logical_id(t) for t in tensor_nodes]
                dim = (
                    int(node.args[1])
                    if len(node.args) > 1 and isinstance(node.args[1], int)
                    else 0
                )

                axis_var = f"axis_{cpp_var}"
                emitter.code_lines.append(
                    f"        int32_t {axis_var} = {dim};"
                )
                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.concat({{ {', '.join(cpp_tensors)} }}, "
                    f"g.constant({{ 1 }}, &{axis_var}, DType::INT32));"
                )

            # 15. Arange
            elif "arange" in op_target_str:
                start, stop, step = 0, 10, 1
                if len(node.args) == 1:
                    stop = (
                        int(node.args[0])
                        if isinstance(node.args[0], int)
                        else 10
                    )
                elif len(node.args) >= 2:
                    start = (
                        int(node.args[0]) if isinstance(node.args[0], int) else 0
                    )
                    stop = (
                        int(node.args[1])
                        if isinstance(node.args[1], int)
                        else 10
                    )
                if len(node.args) >= 3:
                    step = (
                        int(node.args[2]) if isinstance(node.args[2], int) else 1
                    )

                start_id = emitter.ensure_logical_id(start)
                stop_id = emitter.ensure_logical_id(stop)
                step_id = emitter.ensure_logical_id(step)

                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.arange({start_id}, {stop_id}, {step_id});"
                )

            # 16. Sum / Max Reductions
            elif "sum" in op_target_str or "max" in op_target_str:
                id0 = emitter.ensure_logical_id(node.args[0])
                dim = 0
                if len(node.args) > 1:
                    if (
                        isinstance(node.args[1], (list, tuple))
                        and len(node.args[1]) > 0
                    ):
                        dim = int(node.args[1][0])
                    elif isinstance(node.args[1], int):
                        dim = int(node.args[1])
                dim_id = emitter.ensure_logical_id(dim)
                method = "sum" if "sum" in op_target_str else "max"
                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.{method}({id0}, {dim_id});"
                )

            # 17. Reciprocal Square Root (rsqrt)
            elif "rsqrt" in op_target_str:
                id0 = emitter.ensure_logical_id(node.args[0])
                neg_half_id = emitter.ensure_logical_id(-0.5)
                emitter.code_lines.append(
                    f"        LogicalId {cpp_var} = g.pow({id0}, {neg_half_id});"
                )

            # 18. Fallback / Unhandled
            else:
                emitter.code_lines.append(
                    f"        // UNHANDLED ATen Op: {op_target_str} for node {node.name}"
                )

        # C. Output Node
        elif node.op == "output":
            final_node = (
                node.args[0][0]
                if isinstance(node.args[0], (list, tuple))
                else node.args[0]
            )
            emitter.emit_footer(
                final_node.name
                if isinstance(final_node, torch.fx.Node)
                else str(final_node)
            )

    print("[4/4] Writing generated C++ header file...")
    cpp_source = emitter.code_lines
    output_filename = "tensor_graphs_cpp/models/gemma-3-270m-generated.hpp"
    with open(output_filename, "w") as f:
        f.write("\n".join(cpp_source))
    print(f"Successfully generated: {output_filename}")


if __name__ == "__main__":
    transpile_gemma_3()